spring.application.name=springapi

spring.datasource.url=details saved in file
spring.datasource.username= details saved in file
spring.datasource.password= details saved in file


spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
